language: node_js
node_js:
  - 10.18.1
cache:
  directories:
    - node_modules
before_script:
  - yarn add codecov.io coveralls
after_success:
  - yarn run codecov
  - yarn run coveralls
script:
  - yarn run build
  - yarn run test
